language: node_js

sudo: false

cache: yarn

node_js:
  - "8"

install:
  - yarn
  - cd docs && yarn && cd ..

script:
  - yarn test
  - cd docs && yarn test

notifications:
  email: false

after_success:
  - codecov
